import { Quicksand } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full" suppressHydrationWarning>
      <body className={`${quicksand.className} antialiased h-full w-full`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
