import { Quicksand } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar/Navbar";
import Providers from "@/components/providers/Providers";
import { auth } from "@/auth";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // const session = await auth();
  // console.log("-- [app/layout.jsx] SESSION LOG --", session);
  return (
    <html lang="en" className="h-full w-full" suppressHydrationWarning>
      <body className={`${quicksand.className} antialiased h-full w-full`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            {/* Navbar */}
            <Navbar />
            {/* Main content Area */}
            <main className="container mx-auto p-4 md:p-0">{children}</main>

            <Toaster />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
